answer = input("Welke dag van de week kiest u? ")
if answer.lower() == ("Maandag"):
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
elif answer.lower() == ("Dinsdag"):
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
elif answer.lower() == ("Woensdag"):
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
elif answer.lower() == ("Donderdag"):
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
elif answer.lower() == ("Vrijdag"):
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
elif answer.lower() == ("Zaterdag"):
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
elif answer.lower() == ("Zondag"):
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")