answer = input("Welke dag van de week kiest u? ")
if answer == ("Maandag"):
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
elif answer == ("Dinsdag"):
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
elif answer == ("Woensdag"):
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
elif answer == ("Donderdag"):
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
elif answer == ("Vrijdag"):
    print ("Zaterdag")
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
elif answer == ("Zaterdag"):
    print ("Zondag")
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
elif answer == ("Zondag"):
    print ("Maandag")
    print ("Dinsdag")
    print ("Woensdag")
    print ("Donderdag")
    print ("Vrijdag")
    print ("Zaterdag")
    print ("Zondag")
else:
    print ("gebruik een dag")